apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery-container
          image: alexhkhan/celery:latest
          imagePullPolicy: Always
          command:
            [
              "celery",
              "-A",
              "main.celery",
              "worker",
              "--loglevel=info",
              "--uid=nobody",
            ]
          env:
            - name: CELERY_BROKER_URL
              value: "kafka://kafka:9092"
            - name: CELERY_BACKEND_URL
              value: "redis://redis:6379"
